//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 11:31:08 PM FET 
//


package com.example.weapons;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Mass complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Mass">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="complected" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="uncomplected" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Mass", propOrder = {
    "complected",
    "uncomplected"
})
public class Mass {

    protected double complected;
    protected double uncomplected;

    /**
     * Gets the value of the complected property.
     * 
     */
    public double getComplected() {
        return complected;
    }

    /**
     * Sets the value of the complected property.
     * 
     */
    public void setComplected(double value) {
        this.complected = value;
    }

    /**
     * Gets the value of the uncomplected property.
     * 
     */
    public double getUncomplected() {
        return uncomplected;
    }

    /**
     * Sets the value of the uncomplected property.
     * 
     */
    public void setUncomplected(double value) {
        this.uncomplected = value;
    }

}
